### ISSUE TITLE
Support for multiple menus

### ISSUE THREAD

**Issue by jgrietveld** [arielsalminen/TinyNav.js#10]
Hi Viljami,

Thanks for your effort to create this tiny script. I was wondering if it would be possible to use this script on multiple menus on one page? I'm currently running the script twice with 2 different function names, which works fine, but now it's double the size. Is it possible to use the same function on more than one menu at the same time?

Thanks!
Jerry

**Comment by ericmulder1980** [comment]
If you have multiple menu's on your page you should be able to loop over them and activate TinyNav.

Example Markup:
```
<ul class="menu-1 menu">
<li class="active">Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
<ul class="menu-2 menu">
<li class="active">Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
<ul class="menu-3 menu">
<li class="active">Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
```
Example jQuery selector:

```javascript
$('ul.menu').each(function(index){
  $(this).tinyNav({
    header: $(this).find('.active').text(),
    active: 'active'
  });
});
```
